Implement adminRestrictedOpeartion config to support disabling multip…
firebase/firebaseui-web pull request #857
Opened 2021-07-14 01:18 UTC by xil222

…le providers

2021-07-14 01:36 UTC, bojeil-google requested changes

2021-07-14 01:36 UTC, bojeil-google commented on CHANGELOG.md
> +FirebaseUI by defining an adminRestrictedOperation config and adding support in
This has to be a single line. Change to something more understandable and less technical:
` * Improved UI support for all identity provider sign up operations when they are restricted by site administrators.`

2021-07-14 01:36 UTC, bojeil-google commented on soy/elements.soy
> -    <label class="mdl-textfield__label firebaseui-label" for="ui-sign-in-email-input">
You need to revert this change

2021-07-14 01:36 UTC, bojeil-google commented on soy/elements.soy
> -        id="ui-sign-in-email-input"
You need to revert this change

2021-07-14 01:36 UTC, bojeil-google commented on soy/elements.soy
> -      <label class="mdl-textfield__label firebaseui-label" for="ui-sign-in-phone-number-input">
You need to revert this change

2021-07-14 01:36 UTC, bojeil-google commented on soy/elements.soy
> -          id="ui-sign-in-phone-number-input"
You need to revert this change

2021-07-14 01:36 UTC, bojeil-google commented on soy/elements.soy
> -    <label class="mdl-textfield__label firebaseui-label" for="ui-sign-in-phone-confirmation-code-input">
You need to revert this change

2021-07-14 01:36 UTC, bojeil-google commented on soy/elements.soy
> -        id="ui-sign-in-phone-confirmation-code-input"
You need to revert this change

2021-07-14 01:36 UTC, bojeil-google commented on soy/elements.soy
> -    <label class="mdl-textfield__label firebaseui-label" for="ui-sign-in-name-input">
You need to revert this change

2021-07-14 01:36 UTC, bojeil-google commented on soy/elements.soy
> -        id="ui-sign-in-name-input"
You need to revert this change

2021-07-14 01:36 UTC, bojeil-google commented on soy/elements.soy
> -      <label class="mdl-textfield__label firebaseui-label" for="ui-sign-in-new-password-input">
You need to revert this change

2021-07-14 01:36 UTC, bojeil-google commented on soy/elements.soy
> -          id="ui-sign-in-new-password-input"
You need to revert this change

2021-07-14 01:36 UTC, bojeil-google commented on soy/elements.soy
> -    <label class="mdl-textfield__label firebaseui-label" for="ui-sign-in-password-input">
You need to revert this change

2021-07-14 01:36 UTC, bojeil-google commented on soy/elements.soy
> -        id="ui-sign-in-password-input"
You need to revert this change

2021-07-15 06:14 UTC, bojeil-google approved these changes

2021-07-15 21:20 UTC, xil222 commented
@googlebot: rescan

2021-07-15 21:22 UTC, merged